const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Particles,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Behaviors.Turret,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth
	];
};
self.C3_JsPropNameTable = [
	{par_impact_green: 0},
	{par_impact_red: 0},
	{par_impact_blue: 0},
	{Particles: 0},
	{Bullet: 0},
	{Sprite9: 0},
	{Sprite6: 0},
	{bg_game: 0},
	{bg_assets: 0},
	{IsTouched: 0},
	{Health: 0},
	{Solid: 0},
	{"8Direction": 0},
	{Platform: 0},
	{ScrollTo: 0},
	{spr_ship_type1_dark: 0},
	{spr_meteor_red: 0},
	{spr_meteor_green: 0},
	{Physics: 0},
	{spr_meteor_blue: 0},
	{spr_coin: 0},
	{IsPressed: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Turret: 0},
	{spr_ship_enemy_type1: 0},
	{TiledBackground: 0},
	{Sprite5: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Touch: 0},
	{Player_HealthBar: 0},
	{Player_HealthBar_Damage: 0},
	{Enemy_HealthBar_Damage: 0},
	{Enemy_HealthBar: 0},
	{HealthUp: 0},
	{Shield_Button: 0},
	{Sprite7: 0},
	{Player_Shield: 0},
	{Player_Shield_Damage: 0},
	{Sprite8: 0},
	{Score: 0},
	{ShipsDestroyed: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Text: 0},
	{Text2: 0},
	{text_FinalScore: 0},
	{text_TotalShipsDestroyed: 0},
	{bg_speed: 0},
	{EnemyFormation: 0},
	{MeteorRarity: 0}
];

self.InstanceType = {
	par_impact_green: class extends self.IParticlesInstance {},
	par_impact_red: class extends self.IParticlesInstance {},
	par_impact_blue: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bg_game: class extends self.ITiledBackgroundInstance {},
	bg_assets: class extends self.ITiledBackgroundInstance {},
	spr_ship_type1_dark: class extends self.ISpriteInstance {},
	spr_meteor_red: class extends self.ISpriteInstance {},
	spr_meteor_green: class extends self.ISpriteInstance {},
	spr_meteor_blue: class extends self.ISpriteInstance {},
	spr_coin: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	spr_ship_enemy_type1: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Player_HealthBar: class extends self.ISpriteInstance {},
	Player_HealthBar_Damage: class extends self.ISpriteInstance {},
	Enemy_HealthBar_Damage: class extends self.ISpriteInstance {},
	Enemy_HealthBar: class extends self.ISpriteInstance {},
	HealthUp: class extends self.ISpriteInstance {},
	Shield_Button: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Player_Shield: class extends self.ISpriteInstance {},
	Player_Shield_Damage: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	ShipsDestroyed: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	text_FinalScore: class extends self.ITextInstance {},
	text_TotalShipsDestroyed: class extends self.ITextInstance {}
}